### ISSUE TITLE
Managing a secondary key

### ISSUE THREAD

**Issue by ebeauchamps** [edalzell/statamic-linked#5]
Current file with one key ("counties"):

```
counties:
  AL001: Autauga          
  AL003: Baldwin
  AL005: Barbour
```

Could be nice to have a secondary key:

```
counties:
  -
    name: Autauga
    maincity: Toonsville
    population: 2
  -
    name: Baldwin
    maincity: Stataville
    population: 3
  -
    name: Barbour
    maincity: Rainville
    population: 365
```

Primary key == "counties" and secondary key being either "name" or "main city" or "population".
